image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip
    - venv/


before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  
stages:
  - Static Analysis
  - Test
  - Documentation

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
    - pip install pylint-fail-under
    - pylint-fail-under --fail_under 8.0 C0301 src/*.py

pytest:
  stage: Test
  script:
  - pip install pytest
  - pytest -v --ignore=test/ignoreInCI/

pdoc3:
  stage: Documentation
  script:
  - pip install pdoc3
  - pdoc --html src